//  ************************************************************************************************
//
//  Code generating code for piecewise Chebyshev approximation
//
//  Reference: Joachim Wuttke and Alexander Kleinsorge,
//             Algorithm 1XXX: Code generation for piecewise Chebyshev approximation
//
//  File:      src/dem/test_computation.c
//
//  Provides test program test_computation.
//
//  License:   GNU General Public License, version 3 or higher (see src/LICENSE)
//  Copyright: Forschungszentrum Jülich GmbH 2025
//  Author:    Joachim Wuttke <j.wuttke@fz-juelich.de>
//
//  ************************************************************************************************

#include <assert.h>
#include <math.h>
#include <stdio.h>
#include "cerf.h"

#include "auto_test_imwofx.c" // To be generated by the code generator program.

int test_one(double x, double fref)
{
    double fappr = im_w_of_x(x);
    double relerr = fabs((fappr-fref) / fref) / pow(2.,-53);
    if (relerr > ppapp_maxrelerr) {
	printf("x=%23.16e -> fref=%23.16e fappr=%23.16e relerr/eps=%8g tol=%8g\n",
	       x, fref, fappr, relerr, ppapp_maxrelerr);
	return 1;
    }
    return 0;
}

//! Program run_computation.
//! Writes a table of some representative x and f(x), the latter computed in polynomial approximation.

int main() {
    int failed = run_tests();
    if (failed) {
	printf("test_computation: %d test cases failed\n", failed);
	return 1;
    }
    return 0;
}
